Settings As screen:
    Height: =Max(App.Height, App.DesignHeight)
    Width: =Max(App.Width, App.DesignWidth)

    "Gallery3 As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver4.0'":
        Height: =528
        Items: =Steuerdaten
        Layout: =Layout.Vertical
        OnSelect: |-
            =UpdateContext({myItem: ThisItem})
        TemplatePadding: =0
        TemplateSize: =Min(104, Self.Height - 60)
        Y: =110
        ZIndex: =1

        Title4 As label:
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Name
            VerticalAlign: =VerticalAlign.Top
            Width: =Parent.TemplateWidth - 104
            X: =39
            Y: =34
            ZIndex: =1

        Subtitle4 As label:
            Height: =30
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Betrag
            VerticalAlign: =VerticalAlign.Top
            Width: =158
            X: =395
            Y: =37
            ZIndex: =2

        Separator4 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =4

    Label7_1 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(56, 96, 178, 1)
        FontWeight: =FontWeight.Bold
        Height: =110
        Size: =30
        Text: ="Einstellungen"
        Width: =640
        ZIndex: =2

    Button2 As button:
        BorderThickness: =0
        FocusedBorderColor: =Transparent
        Height: =110
        HoverBorderColor: =Transparent
        OnSelect: =Back()
        PressedBorderColor: =Transparent
        Size: =24
        Text: ="Fertig"
        Width: =145
        X: =495
        ZIndex: =3

    Form2 As form:
        DataSource: =Steuerdaten
        Height: =336
        Item: =myItem
        OnSuccess: |-
            =UpdateContext({myItem: Blank()}); UpdateContext({showSave: false})
        Width: =640
        Y: =646
        ZIndex: =4

        Name_DataCard2 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="creb3_name"
            Default: =ThisItem.Name
            DisplayMode: =Parent.DisplayMode
            DisplayName: ="Name"
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@Steuerdaten], DataSourceInfo.MaxLength, "creb3_name")
            Required: =true
            Update: =DataCardValue6.Text
            Width: =640
            X: =0
            Y: =0
            ZIndex: =1

            DataCardKey15 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue6 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Height: =70
                MaxLength: =Parent.MaxLength
                OnChange: |-
                    =UpdateContext({showSave: true})
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey15.Y + DataCardKey15.Height + 5
                ZIndex: =2

            ErrorMessage12 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue6.Y + DataCardValue6.Height
                ZIndex: =3

            StarVisible10 As label:
                Align: =Align.Center
                Height: =DataCardKey15.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey15.Y
                ZIndex: =4

        Betrag_DataCard2 As typedDataCard.numberEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="creb3_betrag"
            Default: =ThisItem.Betrag
            DisplayMode: =Parent.DisplayMode
            DisplayName: ="Betrag"
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            Required: =false
            Update: =Value(DataCardValue11.Text)
            Width: =640
            X: =0
            Y: =1
            ZIndex: =1

            DataCardKey17 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue11 As text:
                Align: =Align.Right
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Format: =TextFormat.Number
                Height: =70
                OnChange: |-
                    =UpdateContext({showSave: true})
                PaddingLeft: =5
                PaddingRight: =20
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =400
                X: =210
                Y: =10
                ZIndex: =2

            ErrorMessage13 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue11.Y + DataCardValue11.Height
                ZIndex: =3

            StarVisible11 As label:
                Align: =Align.Center
                Height: =DataCardKey17.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey17.Y
                ZIndex: =4

        Wert_DataCard1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="creb3_wert"
            Default: =ThisItem.Wert
            DisplayMode: =Parent.DisplayMode
            DisplayName: ="Wert"
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@Steuerdaten], DataSourceInfo.MaxLength, "creb3_wert")
            Required: =false
            Update: =DataCardValue10.Text
            Width: =640
            X: =0
            Y: =2
            ZIndex: =1

            DataCardKey19 As label:
                AutoHeight: =true
                Height: =48
                Size: =21
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue10 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                Height: =70
                MaxLength: =Parent.MaxLength
                OnChange: |-
                    =UpdateContext({showSave: true})
                PaddingLeft: =20
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Size: =21
                Tooltip: =Parent.DisplayName
                Width: =400
                X: =210
                Y: =10
                ZIndex: =2

            ErrorMessage20 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =24
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue10.Y + DataCardValue10.Height
                ZIndex: =3

            StarVisible18 As label:
                Align: =Align.Center
                Height: =DataCardKey19.Height
                Size: =21
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey19.Y
                ZIndex: =4

    Button3 As button:
        Height: =70
        OnSelect: =SubmitForm(Form2)
        Size: =24
        Text: ="Speichern"
        Visible: =showSave
        Width: =280
        X: =180
        Y: =1012
        ZIndex: =5

    labVersion_11 As label:
        Align: =Align.Center
        Color: =RGBA(0, 13, 75, 1)
        Fill: =RGBA(230, 230, 230, 0.53)
        Height: =45
        OnSelect: =Navigate(ScreenVersionen, ScreenTransition.None)
        Size: =16
        Text: ="Version " & LookUp( myVersionen, creb3_index = Max( myVersionen, creb3_index)).version
        Width: =640
        Y: =1091
        ZIndex: =6

